name: example
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.6
  cupertino_icons: ^1.0.2
  permission_handler: ^11.3.1
  phomemo: 
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


dependency_overrides:
  permission_handler_apple:
    path: ../../../GitHub/permission_handler_apple/

flutter:
  uses-material-design: true
