name: phomemo
description: A Flutter plugin to create information to send to phomemo printers.
version: 0.0.1
homepage: https://github.com/Knightro63/phomemo

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^4.0.02
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0